name: Cargo Build & Test

on:
  push:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C link-dead-code"

jobs:
  #call_setup:
  #  uses: ./.github/workflows/setup.yml
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          #- stable
          #- beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo update
      - name: Run tests
        run: cargo test --verbose
